<?php

declare(strict_types=1);

return [
    'admins' => [
        [
            'id' => 1,
            'login' => '2AE351AF-131D-6654-9DB2-79B8F273986C',
            'password' => password_hash('KIS37QEG4HT', PASSWORD_BCRYPT),
            'parent_id' => null,
            'created_at' => '2015-05-14 02:12:05',
            'updated_at' => '2015-06-10 19:30:24',
            'remember_token' => '6A758CB2-234F-F7A1-24FE-4FE263E6FF81',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Lionel Freeman',
            'email' => 'diam.at.pretium@idmollisnec.co.uk',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 2,
            'login' => 'ADCE237A-9E48-BECD-1F01-1CACA964CF0F',
            'password' => password_hash('NKJ63NMV6NY', PASSWORD_BCRYPT),
            'parent_id' => 1,
            'created_at' => '2015-05-14 06:54:01',
            'updated_at' => '2015-05-19 23:48:17',
            'remember_token' => '0A2E7DA9-6072-34E2-38E8-2675C73F3419',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Jasper Waller',
            'email' => 'elit@eratvelpede.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 3,
            'login' => 'FAF56F66-86BB-D3F4-0E94-9E49838F0C11',
            'password' => password_hash('AYI66NCG8FP', PASSWORD_BCRYPT),
            'parent_id' => 1,
            'created_at' => '2015-08-15 17:58:29',
            'updated_at' => '2015-05-09 11:19:45',
            'remember_token' => '45243B45-9C3A-6E61-9292-D5E5CCBDC773',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Chaney Peters',
            'email' => 'volutpat.nunc@vulputate.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 4,
            'login' => 'AB17526A-CAD2-CCBA-25CF-8CCC1D3D4676',
            'password' => password_hash('BGK45ESF9OU', PASSWORD_BCRYPT),
            'parent_id' => 2,
            'created_at' => '2016-04-05 19:59:04',
            'updated_at' => '2015-08-02 16:23:27',
            'remember_token' => '3E6AC914-308F-A622-D06D-4ADB50929EAC',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Wing Davenport',
            'email' => 'dictum.cursus@vulputateveliteu.edu',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 5,
            'login' => '32C8A7EB-2A90-0022-10FE-A108BB3724DA',
            'password' => password_hash('BZU19ONL5RO', PASSWORD_BCRYPT),
            'parent_id' => 3,
            'created_at' => '2016-01-10 23:56:30',
            'updated_at' => '2015-06-20 12:46:46',
            'remember_token' => '769AD022-C17A-22F8-3520-F463A6057333',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Axel Lopez',
            'email' => 'neque@consectetuer.net',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 6,
            'login' => '26B48CE7-3435-E748-57FE-F26CF0501AAB',
            'password' => password_hash('LER18HUL6KQ', PASSWORD_BCRYPT),
            'parent_id' => 4,
            'created_at' => '2016-03-25 13:47:15',
            'updated_at' => '2015-06-26 06:35:48',
            'remember_token' => '7D3A38D8-B134-2CF4-E7DC-BCC30579831B',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Ciaran Mcintosh',
            'email' => 'consectetuer.ipsum.nunc@odioAliquamvulputate.co.uk',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 7,
            'login' => 'A3185AF7-9672-BB7A-ADD6-6440B0535B87',
            'password' => password_hash('TMD18WZD3KC', PASSWORD_BCRYPT),
            'parent_id' => 6,
            'created_at' => '2015-11-12 09:25:17',
            'updated_at' => '2015-09-14 12:51:51',
            'remember_token' => '80E44502-0C65-11F2-EC2A-0FD367B4C4A1',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Thor Hunter',
            'email' => 'et@sapiengravidanon.net',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 8,
            'login' => '00B1EBA4-CF16-97A7-6D3A-C72067E5B6A8',
            'password' => password_hash('RYJ72ALX1TT', PASSWORD_BCRYPT),
            'parent_id' => 2,
            'created_at' => '2015-12-25 01:44:27',
            'updated_at' => '2015-09-03 01:00:36',
            'remember_token' => '9B14DA6D-87B9-0AEE-906B-948B688C82C0',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Neil Mays',
            'email' => 'cursus.luctus.ipsum@egestasa.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 9,
            'login' => '817582E3-ED8C-F00D-CCDE-3380FA305A9C',
            'password' => password_hash('VJV58GCF6PT', PASSWORD_BCRYPT),
            'parent_id' => 8,
            'created_at' => '2015-07-27 18:26:03',
            'updated_at' => '2016-03-29 14:55:58',
            'remember_token' => '1570C42C-63F5-C444-3CE3-71FAB58FCB80',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Baker Holland',
            'email' => 'Nulla.dignissim@ametornarelectus.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 10,
            'login' => '05315DC3-7BD8-06E9-5110-3E7B220C7C47',
            'password' => password_hash('AGX94PSA9VZ', PASSWORD_BCRYPT),
            'parent_id' => 9,
            'created_at' => '2015-06-23 20:00:51',
            'updated_at' => '2016-03-21 15:41:11',
            'remember_token' => 'C20735A9-17D7-1261-B1F0-3FB37FCBDD0A',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Neil Duffy',
            'email' => 'at@nunc.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 11,
            'login' => '6FF85538-560B-33D8-B593-D42ACC0F32A2',
            'password' => password_hash('EPX78IPQ5JP', PASSWORD_BCRYPT),
            'parent_id' => 5,
            'created_at' => '2016-03-14 23:04:52',
            'updated_at' => '2016-04-13 23:28:49',
            'remember_token' => '564BC9A2-22BE-060B-BB04-3019DF07403C',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Marshall Patton',
            'email' => 'turpis@Vivamus.co.uk',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 12,
            'login' => '8ED13AE6-9396-D548-02AC-6D4369F3338B',
            'password' => password_hash('YWN01BQN0VX', PASSWORD_BCRYPT),
            'parent_id' => 10,
            'created_at' => '2015-12-06 01:09:30',
            'updated_at' => '2015-12-27 00:21:56',
            'remember_token' => '9197C74A-254A-8BC0-953C-A12922C687E9',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Otto Oneal',
            'email' => 'augue.porttitor.interdum@ornaresagittisfelis.co.uk',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 13,
            'login' => 'B613F6E2-5184-84ED-9202-BA50C46DAF88',
            'password' => password_hash('LNM09FIH2LG', PASSWORD_BCRYPT),
            'parent_id' => 7,
            'created_at' => '2016-01-14 18:48:15',
            'updated_at' => '2016-03-01 23:44:30',
            'remember_token' => '7A176992-ADA6-F9CF-978E-8FC4C30D03F8',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Wang Franco',
            'email' => 'parturient@tellusNunclectus.ca',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 14,
            'login' => '8E9A3C70-E935-FD78-9F86-8A1D9F72D553',
            'password' => password_hash('YVU41PQU9YH', PASSWORD_BCRYPT),
            'parent_id' => 12,
            'created_at' => '2015-08-27 16:01:44',
            'updated_at' => '2015-09-07 06:06:23',
            'remember_token' => '8180DC8C-D752-1DEF-F3F5-702E535160FB',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Hamilton Vance',
            'email' => 'amet@convallisante.com',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 15,
            'login' => '5F5C7496-AF33-35F0-A027-C1103CA99D9B',
            'password' => password_hash('BGW86BZJ9KG', PASSWORD_BCRYPT),
            'parent_id' => 14,
            'created_at' => '2015-04-27 12:20:18',
            'updated_at' => '2015-12-30 13:50:41',
            'remember_token' => '30710CA1-206B-B058-BE6A-0EB457A6C8F7',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Oren Rocha',
            'email' => 'pulvinar.arcu@necmalesuada.ca',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 16,
            'login' => '0AC15BF1-8E8D-3B5B-9FFF-74E85A0E3EFB',
            'password' => password_hash('UAZ49OYZ8CZ', PASSWORD_BCRYPT),
            'parent_id' => 6,
            'created_at' => '2015-12-22 23:07:49',
            'updated_at' => '2015-09-03 03:09:19',
            'remember_token' => 'DC8E569C-CA1C-4EF8-364C-429CBAFF107F',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Porter Avery',
            'email' => 'leo.Cras@vestibulumneceuismod.com',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 17,
            'login' => '40533991-A6C7-CB71-3B0E-617394B647F7',
            'password' => password_hash('IAO64RHD6CB', PASSWORD_BCRYPT),
            'parent_id' => 14,
            'created_at' => '2016-03-24 16:28:55',
            'updated_at' => '2015-09-14 12:55:10',
            'remember_token' => '1D3EE16E-D8F2-39C2-2C56-8B6369780544',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Michael Workman',
            'email' => 'condimentum@nequetellus.edu',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 18,
            'login' => 'B88806F2-93A0-2A8D-3622-2FA91BCDB64D',
            'password' => password_hash('QOP95YLJ6ZM', PASSWORD_BCRYPT),
            'parent_id' => 7,
            'created_at' => '2015-06-19 17:03:05',
            'updated_at' => '2015-09-10 15:45:03',
            'remember_token' => '3EF2C3B5-B457-92D1-7C78-3CBC907B9826',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Dexter Browning',
            'email' => 'ultrices.posuere@elit.ca',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 19,
            'login' => '988C588F-34A0-5865-FE10-212F98F48CD9',
            'password' => password_hash('SWN37RBS3WP', PASSWORD_BCRYPT),
            'parent_id' => 8,
            'created_at' => '2016-01-25 08:11:13',
            'updated_at' => '2015-06-09 17:04:31',
            'remember_token' => 'C1C29A80-D93F-1190-9FF6-0F04D5F5FBD9',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Duncan Madden',
            'email' => 'erat@enim.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 20,
            'login' => '916AFDB1-93D7-5F51-37AF-744755EC5DF0',
            'password' => password_hash('ELT78ECH5XY', PASSWORD_BCRYPT),
            'parent_id' => 15,
            'created_at' => '2015-10-05 13:44:23',
            'updated_at' => '2015-05-30 15:41:30',
            'remember_token' => 'F120EE9D-2E4F-C1D7-47A5-926198BFBB37',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Gray Watts',
            'email' => 'ornare.lectus.ante@lectusNullam.co.uk',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 21,
            'login' => '06D9145A-36A1-5381-A9DE-3ED263750E9D',
            'password' => password_hash('PWO44SIT6IG', PASSWORD_BCRYPT),
            'parent_id' => 4,
            'created_at' => '2016-03-13 03:01:54',
            'updated_at' => '2016-01-12 04:09:30',
            'remember_token' => '13CC5C3D-8405-4949-9FE0-438CF9113D1D',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Jordan Fisher',
            'email' => 'Sed.nunc@Proinmi.org',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 22,
            'login' => '98CA9E6A-7BDD-4169-544B-5CFFF86EB7A9',
            'password' => password_hash('FLS58YXL5QW', PASSWORD_BCRYPT),
            'parent_id' => 15,
            'created_at' => '2015-09-20 18:34:42',
            'updated_at' => '2016-01-07 10:41:21',
            'remember_token' => 'B95FA555-31FD-0781-FFFA-5DA258AF2FA9',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Kamal Richardson',
            'email' => 'Aliquam.vulputate.ullamcorper@sapienimperdiet.com',
            'timezone' => 'Europe/Moscow',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 23,
            'login' => 'A046F339-BB06-B829-434C-540D9DFA9AFD',
            'password' => password_hash('AES19JLL7VQ', PASSWORD_BCRYPT),
            'parent_id' => 3,
            'created_at' => '2016-02-10 13:58:07',
            'updated_at' => '2016-02-21 15:02:35',
            'remember_token' => 'FEBB4F14-1946-B6DC-9610-00048FAFBAD8',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Ulric Knight',
            'email' => 'auctor.velit.eget@dictum.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 24,
            'login' => 'A7891C67-1902-DAC4-277A-8C2723446820',
            'password' => password_hash('DFY80CMN3UI', PASSWORD_BCRYPT),
            'parent_id' => 10,
            'created_at' => '2015-07-13 17:08:44',
            'updated_at' => '2015-07-09 17:03:06',
            'remember_token' => 'A16893F0-CD64-FD2B-CECB-66CD31ABD7BE',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Tanner Lowe',
            'email' => 'sed@ante.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 25,
            'login' => 'F2707455-5E87-96E7-9AC5-A1ECF3894C30',
            'password' => password_hash('TCM76VKP7QG', PASSWORD_BCRYPT),
            'parent_id' => 17,
            'created_at' => '2016-01-09 23:28:47',
            'updated_at' => '2015-12-14 11:47:44',
            'remember_token' => '372AA576-4563-4166-6133-FDD55EF3CDD6',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Barclay Ortiz',
            'email' => 'odio.tristique@semperNam.com',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 26,
            'login' => 'AAEF82DD-A678-A868-C1D4-C54A4E76BFC7',
            'password' => password_hash('UFW15TKC7CJ', PASSWORD_BCRYPT),
            'parent_id' => 16,
            'created_at' => '2016-03-25 10:29:16',
            'updated_at' => '2015-11-01 01:43:16',
            'remember_token' => '6010F7FA-857A-0928-3BC1-F8C83E0B26DD',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Lars Mejia',
            'email' => 'neque.pellentesque.massa@Donecegestas.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 27,
            'login' => 'CE9D5D92-FA42-5DCC-3E7A-87D68300B450',
            'password' => password_hash('LTQ23UWK1LR', PASSWORD_BCRYPT),
            'parent_id' => 11,
            'created_at' => '2015-11-30 18:18:16',
            'updated_at' => '2016-02-01 12:55:54',
            'remember_token' => 'DAEEBAF7-B59A-4F06-0972-720909D6B67E',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Logan Bowen',
            'email' => 'in.faucibus@mi.edu',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 28,
            'login' => 'A1D154F3-DD47-1E7A-430E-D1F05F0652A1',
            'password' => password_hash('MKM13UNA5WK', PASSWORD_BCRYPT),
            'parent_id' => 19,
            'created_at' => '2016-01-26 15:15:51',
            'updated_at' => '2015-10-07 14:30:26',
            'remember_token' => '16D79B37-4338-24C4-1886-8AA6074A55FE',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Brenden Gregory',
            'email' => 'enim.diam@morbi.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 29,
            'login' => '7E0E58E8-D2D6-45FF-6278-10C270D512A6',
            'password' => password_hash('ZYR72AAS3EX', PASSWORD_BCRYPT),
            'parent_id' => 11,
            'created_at' => '2015-08-02 16:25:01',
            'updated_at' => '2015-06-08 09:21:49',
            'remember_token' => '9D950181-795E-20BE-45FF-0AF89015D82D',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Julian Joyner',
            'email' => 'id.magna.et@a.net',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 30,
            'login' => 'A60BCBCE-7040-86AA-6A36-9EA859F67250',
            'password' => password_hash('ZCM73JLN8FM', PASSWORD_BCRYPT),
            'parent_id' => 27,
            'created_at' => '2015-09-14 23:49:04',
            'updated_at' => '2015-05-09 22:39:16',
            'remember_token' => '41A3DC30-E26B-ECBD-0274-CF5009DEDC3C',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Joel Neal',
            'email' => 'Ut.tincidunt@sem.com',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 31,
            'login' => '311F153F-8D8F-97EB-93A8-FC9BF3E1FA04',
            'password' => password_hash('ZYC89EKV2FU', PASSWORD_BCRYPT),
            'parent_id' => 29,
            'created_at' => '2016-01-23 23:50:20',
            'updated_at' => '2015-08-23 11:32:06',
            'remember_token' => 'FACEB366-5097-BE12-4B79-5BBC60359656',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Wallace Mcguire',
            'email' => 'magnis.dis.parturient@enim.net',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 32,
            'login' => '01188F52-2F30-4E2E-2B41-E5406769543A',
            'password' => password_hash('LIL60ATH6QC', PASSWORD_BCRYPT),
            'parent_id' => 26,
            'created_at' => '2015-05-10 23:57:56',
            'updated_at' => '2015-04-29 15:33:04',
            'remember_token' => '98CFB419-3F94-B99F-2ED5-045D7501F790',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Judah Page',
            'email' => 'vehicula@enimcondimentum.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 33,
            'login' => '7C8B1023-0CE8-B2D0-57B3-AF7CDA5A6692',
            'password' => password_hash('BTR64GDB9YK', PASSWORD_BCRYPT),
            'parent_id' => 25,
            'created_at' => '2015-08-25 22:14:36',
            'updated_at' => '2016-01-11 07:34:37',
            'remember_token' => '94168A67-8674-CA6D-BF74-823E9B914E7D',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Troy Torres',
            'email' => 'non.enim@magna.co.uk',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 34,
            'login' => '610EE205-C658-795A-39B8-8C7437736AFB',
            'password' => password_hash('MSJ06XCR1PY', PASSWORD_BCRYPT),
            'parent_id' => 20,
            'created_at' => '2015-11-14 15:31:43',
            'updated_at' => '2015-11-22 03:00:53',
            'remember_token' => '0D658E9B-5D44-E125-8599-498BFE3D5B40',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Howard Mcintosh',
            'email' => 'nec.urna@Donecegestas.org',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 35,
            'login' => '259A9C6E-0E5C-3025-7492-99C64740FF02',
            'password' => password_hash('BPI21KIG9EH', PASSWORD_BCRYPT),
            'parent_id' => 33,
            'created_at' => '2015-10-04 08:35:08',
            'updated_at' => '2016-03-21 01:43:22',
            'remember_token' => 'C0457AB9-9AD9-7115-F20B-1931412C04B9',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Norman Bates',
            'email' => 'hendrerit@nequetellusimperdiet.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 36,
            'login' => '69E98BA4-952D-2F67-8AE5-1047DDA3764A',
            'password' => password_hash('WKN25SOP7BU', PASSWORD_BCRYPT),
            'parent_id' => 23,
            'created_at' => '2015-07-16 06:51:38',
            'updated_at' => '2016-03-27 04:57:23',
            'remember_token' => 'E8DE088B-71BB-2A3B-AB20-9178EBDF6E1F',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Josiah Kirkland',
            'email' => 'metus@NullamenimSed.com',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 37,
            'login' => 'A667DC71-44DD-E28B-A404-07BCB823A95D',
            'password' => password_hash('QTC44FUL3GL', PASSWORD_BCRYPT),
            'parent_id' => 34,
            'created_at' => '2016-03-20 21:20:10',
            'updated_at' => '2016-04-04 14:06:47',
            'remember_token' => 'ECC1F209-1BDC-997C-9682-50459C99D8D9',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Dillon Adkins',
            'email' => 'ullamcorper.nisl.arcu@et.edu',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 38,
            'login' => '9693B8C5-3105-BFD4-ACF1-3FF5BA971FCA',
            'password' => password_hash('HBL00GFH4XZ', PASSWORD_BCRYPT),
            'parent_id' => 13,
            'created_at' => '2015-06-29 13:36:39',
            'updated_at' => '2015-12-29 01:40:09',
            'remember_token' => '7807721E-474C-8AD5-68A8-BE2E8DBECED0',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Stephen Acosta',
            'email' => 'nonummy.ut@diamProindolor.net',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 39,
            'login' => '254E3B01-84AD-7832-3B7E-DCD457151D20',
            'password' => password_hash('FZG05MQJ0ZG', PASSWORD_BCRYPT),
            'parent_id' => 31,
            'created_at' => '2015-06-26 10:02:10',
            'updated_at' => '2015-05-24 02:46:17',
            'remember_token' => 'FB1C9571-065E-BDA4-5ECB-3534342BC247',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Sylvester Serrano',
            'email' => 'sit@posuere.net',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 40,
            'login' => '4F25BA5B-678F-2DBE-28AA-7597AA897658',
            'password' => password_hash('RQX37TKF6MU', PASSWORD_BCRYPT),
            'parent_id' => 23,
            'created_at' => '2015-10-29 00:05:54',
            'updated_at' => '2015-10-03 07:36:32',
            'remember_token' => '10742F52-B126-0DFE-057C-8DB1710BA41E',
            'is_superadmin' => true,
            'language' => 'ru',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Melvin Barry',
            'email' => 'a.sollicitudin@IntegermollisInteger.org',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 41,
            'login' => 'C43163E9-5F50-C139-CDA0-0B2CB55B1E1C',
            'password' => password_hash('UQU45RPL5CA', PASSWORD_BCRYPT),
            'parent_id' => 21,
            'created_at' => '2015-11-18 06:30:27',
            'updated_at' => '2016-01-16 16:13:54',
            'remember_token' => '0824204A-0EEC-088D-3D3E-B1974DBEFB63',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Judah Macdonald',
            'email' => 'justo.nec@elitEtiamlaoreet.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 42,
            'login' => 'FEE0C2D1-0268-8532-AA66-7BC859F72E89',
            'password' => password_hash('HFA06MQB6RS', PASSWORD_BCRYPT),
            'parent_id' => 18,
            'created_at' => '2015-08-19 12:43:12',
            'updated_at' => '2015-09-04 16:19:03',
            'remember_token' => 'B09DB803-FB49-11EA-CF3D-DA73E122B455',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Malcolm Hubbard',
            'email' => 'nunc@facilisiseget.net',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 43,
            'login' => '9BC8EF55-3FA9-2A8F-A167-F7AC81E6F4D5',
            'password' => password_hash('RNI14LJG7LH', PASSWORD_BCRYPT),
            'parent_id' => 19,
            'created_at' => '2015-12-23 22:33:00',
            'updated_at' => '2016-03-21 07:26:40',
            'remember_token' => 'E454980D-C868-460F-493E-A78407508507',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Evan Battle',
            'email' => 'massa.lobortis@facilisis.org',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 44,
            'login' => 'D7F58E39-8B69-13A1-D0E9-094C90A45726',
            'password' => password_hash('IPC97IXY1LZ', PASSWORD_BCRYPT),
            'parent_id' => 16,
            'created_at' => '2015-11-28 03:34:26',
            'updated_at' => '2016-01-13 21:19:12',
            'remember_token' => '4EFAD026-C739-8481-6A78-2E607F161399',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Mark Key',
            'email' => 'Nulla@sit.net',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 45,
            'login' => '39A7F3E9-E210-AA3C-1335-8C3CDCE45C24',
            'password' => password_hash('BOQ92ULK2XA', PASSWORD_BCRYPT),
            'parent_id' => 34,
            'created_at' => '2015-09-04 13:48:29',
            'updated_at' => '2015-06-18 10:01:26',
            'remember_token' => 'B8CCA88E-5138-BAD3-ED72-D6BB5A973305',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Talon Hanson',
            'email' => 'vehicula.risus.Nulla@egetmollis.co.uk',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 46,
            'login' => 'EE247619-4F24-9F1B-06F5-E28AAE3EDCE6',
            'password' => password_hash('LAA13DVX4YK', PASSWORD_BCRYPT),
            'parent_id' => 27,
            'created_at' => '2015-10-05 02:17:58',
            'updated_at' => '2015-05-15 18:10:41',
            'remember_token' => 'DF4D41A4-C9A7-BE80-2F1D-CABAD885AD8E',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'manager',
            'is_active' => true,
            'name' => 'Oscar Bates',
            'email' => 'et.risus.Quisque@Crasvulputate.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 47,
            'login' => 'F24B3CD6-A897-00AB-7109-3F9A1D25F609',
            'password' => password_hash('UKR18OIB5ED', PASSWORD_BCRYPT),
            'parent_id' => 28,
            'created_at' => '2015-11-03 21:51:54',
            'updated_at' => '2016-03-11 09:15:35',
            'remember_token' => '5B9C5E34-EA2A-E2EF-05B5-C3BCAC759A3B',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Fuller Goodwin',
            'email' => 'fringilla.Donec@estmaurisrhoncus.ca',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 48,
            'login' => '562B2659-F8DF-1306-40F9-5D05406A8FD9',
            'password' => password_hash('UMG74XFA8EZ', PASSWORD_BCRYPT),
            'parent_id' => 28,
            'created_at' => '2015-10-09 21:47:13',
            'updated_at' => '2015-06-27 22:39:49',
            'remember_token' => '1F593E3B-77A2-1B1A-12B0-E040A95DFEAB',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'guest',
            'is_active' => true,
            'name' => 'Ivor Powers',
            'email' => 'id@sed.edu',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 49,
            'login' => '746FEBA3-5FF0-5415-C730-3D018EFBA234',
            'password' => password_hash('ISU54MRO8CV', PASSWORD_BCRYPT),
            'parent_id' => 36,
            'created_at' => '2015-08-24 06:06:18',
            'updated_at' => '2016-03-22 04:15:20',
            'remember_token' => '6177B621-DBB0-1290-FD05-CA2C56891586',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Phillip Logan',
            'email' => 'elit.a@tristiquepellentesquetellus.co.uk',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
        [
            'id' => 50,
            'login' => '749C2E87-4CB7-E4F6-D65E-975A4E2B3026',
            'password' => password_hash('GJN97TXS0JA', PASSWORD_BCRYPT),
            'parent_id' => 46,
            'created_at' => '2015-05-15 21:11:38',
            'updated_at' => '2015-12-11 13:48:00',
            'remember_token' => '41579014-EBFD-60A2-08A1-1F735A96662A',
            'is_superadmin' => true,
            'language' => 'en',
            'ip' => '192.168.0.1',
            'role' => 'admin',
            'is_active' => true,
            'name' => 'Merrill Malone',
            'email' => 'fringilla@nonleoVivamus.com',
            'timezone' => 'UTC',
            'not_changeable_column' => 'not changable',
            'big_data' => null,
        ],
    ],
    'info_pages' => [
        [
            'id' => 1,
            'code' => 'Non Lacinia At Incorporated',
            'lang' => 'en',
            'title' => 'penatibus et magnis dis parturient montes,',
            'link_title' => 'est. Nunc ullamcorper,',
            'content' => 'convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla',
            'is_important' => true,
            'created_at' => '2016-06-17 21:10:29',
            'updated_at' => '2016-06-02 20:32:41',
        ],
        [
            'id' => 2,
            'code' => 'Lorem Luctus Inc.',
            'lang' => 'en',
            'title' => 'adipiscing elit. Etiam laoreet, libero et tristique',
            'link_title' => 'faucibus orci luctus',
            'content' => 'neque. In ornare sagittis felis. Donec tempor,',
            'is_important' => true,
            'created_at' => '2016-10-29 20:35:06',
            'updated_at' => '2015-07-17 16:55:41',
        ],
        [
            'id' => 3,
            'code' => 'Magna Corporation',
            'lang' => 'ru',
            'title' => 'odio tristique pharetra. Quisque ac',
            'link_title' => 'magna a',
            'content' => 'et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non,',
            'is_important' => true,
            'created_at' => '2016-10-07 09:37:14',
            'updated_at' => '2016-02-04 23:49:49',
        ],
        [
            'id' => 4,
            'code' => 'Eu LLC',
            'lang' => 'ru',
            'title' => 'sem eget massa. Suspendisse eleifend.',
            'link_title' => 'egestas lacinia. Sed congue,',
            'content' => 'justo sit amet nulla. Donec non justo.',
            'is_important' => true,
            'created_at' => '2017-04-12 02:23:35',
            'updated_at' => '2016-09-26 06:11:09',
        ],
        [
            'id' => 5,
            'code' => 'Amet Orci Ut Ltd',
            'lang' => 'en',
            'title' => 'Mauris vestibulum, neque sed',
            'link_title' => 'Aliquam gravida',
            'content' => 'a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum',
            'is_important' => true,
            'created_at' => '2015-08-19 08:10:19',
            'updated_at' => '2016-08-12 11:17:07',
        ],
        [
            'id' => 6,
            'code' => 'Integer Vitae Ltd',
            'lang' => 'en',
            'title' => 'sit amet, consectetuer adipiscing',
            'link_title' => 'ligula. Aenean euismod',
            'content' => 'elit. Etiam laoreet, libero et tristique pellentesque, tellus sem',
            'is_important' => true,
            'created_at' => '2015-11-25 19:23:32',
            'updated_at' => '2015-09-03 14:26:32',
        ],
        [
            'id' => 7,
            'code' => 'Maecenas Libero Foundation',
            'lang' => 'ru',
            'title' => 'velit in aliquet lobortis,',
            'link_title' => 'ornare, lectus ante dictum mi,',
            'content' => 'Donec egestas. Aliquam nec enim. Nunc ut',
            'is_important' => true,
            'created_at' => '2016-08-14 12:52:48',
            'updated_at' => '2017-01-26 09:32:13',
        ],
        [
            'id' => 8,
            'code' => 'Fringilla Mi Lacinia LLP',
            'lang' => 'ru',
            'title' => 'ipsum. Donec sollicitudin adipiscing ligula. Aenean',
            'link_title' => 'mauris. Suspendisse',
            'content' => 'feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget,',
            'is_important' => true,
            'created_at' => '2016-09-26 22:28:52',
            'updated_at' => '2016-12-23 18:57:40',
        ],
        [
            'id' => 9,
            'code' => 'Suspendisse Company',
            'lang' => 'en',
            'title' => 'Morbi accumsan laoreet',
            'link_title' => 'dis parturient montes, nascetur',
            'content' => 'magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo.',
            'is_important' => true,
            'created_at' => '2017-02-12 10:03:17',
            'updated_at' => '2015-04-24 12:03:24',
        ],
        [
            'id' => 10,
            'code' => 'Blandit PC',
            'lang' => 'en',
            'title' => 'sagittis felis. Donec tempor, est ac',
            'link_title' => 'magna a neque.',
            'content' => 'arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros',
            'is_important' => true,
            'created_at' => '2016-05-05 03:54:29',
            'updated_at' => '2015-09-23 00:59:13',
        ],
        [
            'id' => 11,
            'code' => 'Turpis Non Enim Consulting',
            'lang' => 'ru',
            'title' => 'dignissim pharetra. Nam ac nulla. In tincidunt',
            'link_title' => 'massa lobortis',
            'content' => 'Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique',
            'is_important' => true,
            'created_at' => '2016-09-10 22:33:07',
            'updated_at' => '2015-10-14 20:33:22',
        ],
        [
            'id' => 12,
            'code' => 'Fermentum Convallis LLC',
            'lang' => 'ru',
            'title' => 'cursus, diam at pretium aliquet,',
            'link_title' => 'consectetuer adipiscing elit.',
            'content' => 'semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum',
            'is_important' => true,
            'created_at' => '2015-06-13 12:00:12',
            'updated_at' => '2016-07-28 12:23:35',
        ],
        [
            'id' => 13,
            'code' => 'Dictum Corporation',
            'lang' => 'en',
            'title' => 'tincidunt tempus risus.',
            'link_title' => 'nisl elementum purus,',
            'content' => 'Phasellus dolor elit, pellentesque a,',
            'is_important' => true,
            'created_at' => '2016-07-15 17:14:38',
            'updated_at' => '2015-11-29 10:06:29',
        ],
        [
            'id' => 14,
            'code' => 'Cras Interdum Nunc Foundation',
            'lang' => 'en',
            'title' => 'Proin sed turpis nec mauris',
            'link_title' => 'ac orci.',
            'content' => 'amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl',
            'is_important' => true,
            'created_at' => '2015-10-28 12:10:07',
            'updated_at' => '2016-12-08 09:19:57',
        ],
        [
            'id' => 15,
            'code' => 'Vitae Aliquet Corporation',
            'lang' => 'ru',
            'title' => 'a sollicitudin orci sem',
            'link_title' => 'sollicitudin commodo ipsum. Suspendisse',
            'content' => 'quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus',
            'is_important' => true,
            'created_at' => '2016-05-22 10:31:07',
            'updated_at' => '2016-01-10 18:20:55',
        ],
        [
            'id' => 16,
            'code' => 'Tellus Suspendisse Sed Corp.',
            'lang' => 'ru',
            'title' => 'natoque penatibus et magnis dis parturient montes,',
            'link_title' => 'nec tellus. Nunc lectus',
            'content' => 'dictum. Proin eget odio. Aliquam vulputate',
            'is_important' => true,
            'created_at' => '2015-10-23 14:54:53',
            'updated_at' => '2016-11-18 03:22:42',
        ],
        [
            'id' => 17,
            'code' => 'Suspendisse Tristique Neque Institute',
            'lang' => 'en',
            'title' => 'dolor egestas rhoncus. Proin nisl sem,',
            'link_title' => 'lorem fringilla ornare placerat, orci',
            'content' => 'auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis',
            'is_important' => true,
            'created_at' => '2016-08-09 21:14:14',
            'updated_at' => '2016-08-19 20:49:33',
        ],
        [
            'id' => 18,
            'code' => 'Eros Industries',
            'lang' => 'en',
            'title' => 'sociosqu ad litora torquent',
            'link_title' => 'nulla vulputate dui,',
            'content' => 'convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec',
            'is_important' => true,
            'created_at' => '2015-10-16 19:53:08',
            'updated_at' => '2017-02-03 22:59:21',
        ],
        [
            'id' => 19,
            'code' => 'Mauris Magna Institute',
            'lang' => 'ru',
            'title' => 'ultrices iaculis odio. Nam interdum enim non',
            'link_title' => 'commodo hendrerit.',
            'content' => 'imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in,',
            'is_important' => true,
            'created_at' => '2015-09-15 04:02:59',
            'updated_at' => '2017-04-02 18:30:42',
        ],
        [
            'id' => 20,
            'code' => 'Turpis Egestas Corporation',
            'lang' => 'ru',
            'title' => 'eget, ipsum. Donec sollicitudin',
            'link_title' => 'risus. Morbi metus. Vivamus',
            'content' => 'Suspendisse non leo. Vivamus nibh',
            'is_important' => true,
            'created_at' => '2017-02-15 21:41:48',
            'updated_at' => '2016-12-21 03:31:45',
        ],
        [
            'id' => 21,
            'code' => 'Ante Dictum Ltd',
            'lang' => 'en',
            'title' => 'dignissim lacus. Aliquam rutrum',
            'link_title' => 'tempor augue',
            'content' => 'magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis',
            'is_important' => true,
            'created_at' => '2015-08-13 00:05:20',
            'updated_at' => '2017-01-16 06:00:33',
        ],
        [
            'id' => 22,
            'code' => 'Sem Consequat Industries',
            'lang' => 'en',
            'title' => 'laoreet, libero et tristique pellentesque, tellus',
            'link_title' => 'risus. In mi pede, nonummy',
            'content' => 'egestas a, dui. Cras pellentesque. Sed dictum. Proin',
            'is_important' => true,
            'created_at' => '2017-01-14 21:58:02',
            'updated_at' => '2016-06-29 02:38:32',
        ],
        [
            'id' => 23,
            'code' => 'Laoreet Posuere Enim LLC',
            'lang' => 'ru',
            'title' => 'odio. Aliquam vulputate',
            'link_title' => 'sed, est. Nunc laoreet lectus',
            'content' => 'nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat',
            'is_important' => true,
            'created_at' => '2016-07-29 20:10:14',
            'updated_at' => '2016-07-21 16:05:16',
        ],
        [
            'id' => 24,
            'code' => 'In Felis Nulla Ltd',
            'lang' => 'ru',
            'title' => 'Maecenas malesuada fringilla est. Mauris eu turpis.',
            'link_title' => 'at, iaculis',
            'content' => 'sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,',
            'is_important' => true,
            'created_at' => '2015-12-19 01:38:52',
            'updated_at' => '2017-02-20 13:07:30',
        ],
        [
            'id' => 25,
            'code' => 'Eu Corporation',
            'lang' => 'en',
            'title' => 'amet lorem semper auctor.',
            'link_title' => 'dapibus gravida. Aliquam tincidunt,',
            'content' => 'consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor.',
            'is_important' => true,
            'created_at' => '2017-03-02 06:55:10',
            'updated_at' => '2017-03-03 10:04:48',
        ],
        [
            'id' => 26,
            'code' => 'Et Incorporated',
            'lang' => 'en',
            'title' => 'nonummy ipsum non arcu. Vivamus',
            'link_title' => 'libero est,',
            'content' => 'volutpat ornare, facilisis eget, ipsum.',
            'is_important' => true,
            'created_at' => '2016-12-09 03:25:21',
            'updated_at' => '2015-08-25 11:17:44',
        ],
        [
            'id' => 27,
            'code' => 'Purus Mauris Foundation',
            'lang' => 'ru',
            'title' => 'nonummy ac, feugiat',
            'link_title' => 'a, magna. Lorem',
            'content' => 'elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy',
            'is_important' => true,
            'created_at' => '2016-02-17 07:51:17',
            'updated_at' => '2016-10-08 08:56:10',
        ],
        [
            'id' => 28,
            'code' => 'Ac Inc.',
            'lang' => 'ru',
            'title' => 'orci. Donec nibh. Quisque nonummy ipsum non',
            'link_title' => 'Quisque tincidunt pede',
            'content' => 'cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus',
            'is_important' => true,
            'created_at' => '2015-05-05 12:21:52',
            'updated_at' => '2016-08-05 15:06:16',
        ],
        [
            'id' => 29,
            'code' => 'Aliquam Erat Volutpat LLC',
            'lang' => 'en',
            'title' => 'non dui nec urna',
            'link_title' => 'id, libero. Donec consectetuer',
            'content' => 'Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer',
            'is_important' => true,
            'created_at' => '2016-01-06 08:11:51',
            'updated_at' => '2015-05-18 03:08:01',
        ],
        [
            'id' => 30,
            'code' => 'Aliquet Metus Urna Institute',
            'lang' => 'en',
            'title' => 'Cum sociis natoque penatibus et',
            'link_title' => 'Donec luctus aliquet odio.',
            'content' => 'enim, condimentum eget, volutpat ornare, facilisis',
            'is_important' => true,
            'created_at' => '2016-03-24 06:16:58',
            'updated_at' => '2016-05-06 06:01:10',
        ],
        [
            'id' => 31,
            'code' => 'Est Mauris Rhoncus PC',
            'lang' => 'ru',
            'title' => 'nec, diam. Duis mi',
            'link_title' => 'diam vel',
            'content' => 'malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna.',
            'is_important' => true,
            'created_at' => '2016-11-06 13:14:40',
            'updated_at' => '2016-03-23 00:08:10',
        ],
        [
            'id' => 32,
            'code' => 'Mi Eleifend Company',
            'lang' => 'ru',
            'title' => 'imperdiet nec, leo.',
            'link_title' => 'euismod urna. Nullam lobortis',
            'content' => 'ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et,',
            'is_important' => true,
            'created_at' => '2016-10-12 16:57:54',
            'updated_at' => '2015-10-03 13:10:27',
        ],
        [
            'id' => 33,
            'code' => 'Sed Associates',
            'lang' => 'en',
            'title' => 'felis ullamcorper viverra. Maecenas iaculis aliquet diam.',
            'link_title' => 'lacus. Etiam bibendum',
            'content' => 'mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor',
            'is_important' => true,
            'created_at' => '2016-06-30 19:28:34',
            'updated_at' => '2015-09-12 13:16:46',
        ],
        [
            'id' => 34,
            'code' => 'Donec LLP',
            'lang' => 'en',
            'title' => 'Nulla eget metus',
            'link_title' => 'cursus. Integer mollis. Integer tincidunt',
            'content' => 'Pellentesque habitant morbi tristique senectus et netus et malesuada',
            'is_important' => true,
            'created_at' => '2015-06-14 07:19:25',
            'updated_at' => '2015-10-19 14:54:58',
        ],
        [
            'id' => 35,
            'code' => 'Feugiat Sed Nec Inc.',
            'lang' => 'ru',
            'title' => 'ante lectus convallis est, vitae',
            'link_title' => 'lectus, a sollicitudin',
            'content' => 'eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede',
            'is_important' => true,
            'created_at' => '2016-07-27 22:05:05',
            'updated_at' => '2017-01-11 09:56:15',
        ],
        [
            'id' => 36,
            'code' => 'Purus Corporation',
            'lang' => 'ru',
            'title' => 'tincidunt adipiscing. Mauris',
            'link_title' => 'ipsum cursus vestibulum.',
            'content' => 'ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae,',
            'is_important' => true,
            'created_at' => '2016-08-18 11:30:47',
            'updated_at' => '2015-10-20 20:53:28',
        ],
        [
            'id' => 37,
            'code' => 'Odio Limited',
            'lang' => 'en',
            'title' => 'id, ante. Nunc mauris sapien, cursus in,',
            'link_title' => 'at, velit. Cras lorem',
            'content' => 'accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam,',
            'is_important' => true,
            'created_at' => '2016-03-15 09:17:25',
            'updated_at' => '2017-03-21 02:44:51',
        ],
        [
            'id' => 38,
            'code' => 'Viverra Limited',
            'lang' => 'en',
            'title' => 'mi tempor lorem, eget',
            'link_title' => 'Aliquam ultrices',
            'content' => 'pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed',
            'is_important' => true,
            'created_at' => '2016-04-10 12:49:57',
            'updated_at' => '2017-03-25 02:05:33',
        ],
        [
            'id' => 39,
            'code' => 'Vel Foundation',
            'lang' => 'ru',
            'title' => 'cursus in, hendrerit',
            'link_title' => 'elementum sem,',
            'content' => 'faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa',
            'is_important' => true,
            'created_at' => '2017-02-21 02:09:11',
            'updated_at' => '2016-12-13 09:52:25',
        ],
        [
            'id' => 40,
            'code' => 'Sagittis Lobortis Mauris LLC',
            'lang' => 'ru',
            'title' => 'ut aliquam iaculis, lacus pede sagittis augue,',
            'link_title' => 'orci tincidunt',
            'content' => 'Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at',
            'is_important' => true,
            'created_at' => '2016-07-02 19:03:01',
            'updated_at' => '2015-09-18 14:43:19',
        ],
        [
            'id' => 41,
            'code' => 'Nec Enim Nunc LLP',
            'lang' => 'en',
            'title' => 'ac nulla. In tincidunt',
            'link_title' => 'imperdiet nec,',
            'content' => 'In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod',
            'is_important' => true,
            'created_at' => '2015-06-23 21:23:07',
            'updated_at' => '2016-12-16 14:07:54',
        ],
        [
            'id' => 42,
            'code' => 'Convallis Foundation',
            'lang' => 'en',
            'title' => 'placerat, augue. Sed molestie.',
            'link_title' => 'Phasellus nulla. Integer',
            'content' => 'urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus',
            'is_important' => true,
            'created_at' => '2015-10-20 19:00:44',
            'updated_at' => '2016-03-18 04:50:26',
        ],
        [
            'id' => 43,
            'code' => 'Suspendisse Sagittis LLP',
            'lang' => 'ru',
            'title' => 'non, bibendum sed, est. Nunc laoreet',
            'link_title' => 'ornare egestas',
            'content' => 'tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,',
            'is_important' => true,
            'created_at' => '2016-12-20 10:37:19',
            'updated_at' => '2015-07-25 06:37:43',
        ],
        [
            'id' => 44,
            'code' => 'Quis Lectus Foundation',
            'lang' => 'ru',
            'title' => 'neque. In ornare sagittis felis.',
            'link_title' => 'Nulla tincidunt, neque',
            'content' => 'pharetra. Nam ac nulla. In tincidunt',
            'is_important' => true,
            'created_at' => '2016-04-23 01:57:21',
            'updated_at' => '2017-01-03 04:37:46',
        ],
        [
            'id' => 45,
            'code' => 'Erat Vitae Risus PC',
            'lang' => 'en',
            'title' => 'et magnis dis parturient montes, nascetur',
            'link_title' => 'tristique pharetra. Quisque ac libero',
            'content' => 'parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed',
            'is_important' => true,
            'created_at' => '2016-03-16 17:34:19',
            'updated_at' => '2015-04-30 15:52:50',
        ],
        [
            'id' => 46,
            'code' => 'Montes Nascetur Ridiculus LLC',
            'lang' => 'en',
            'title' => 'ac arcu. Nunc mauris. Morbi',
            'link_title' => 'ut lacus. Nulla tincidunt,',
            'content' => 'Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam',
            'is_important' => true,
            'created_at' => '2017-03-25 04:29:31',
            'updated_at' => '2015-08-30 12:07:20',
        ],
        [
            'id' => 47,
            'code' => 'Sit Amet Corp.',
            'lang' => 'ru',
            'title' => 'augue scelerisque mollis.',
            'link_title' => 'montes, nascetur ridiculus mus.',
            'content' => 'netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper',
            'is_important' => true,
            'created_at' => '2017-03-20 13:15:59',
            'updated_at' => '2016-06-13 09:55:56',
        ],
        [
            'id' => 48,
            'code' => 'Interdum Institute',
            'lang' => 'ru',
            'title' => 'ridiculus mus. Proin vel nisl.',
            'link_title' => 'Curae Phasellus ornare.',
            'content' => 'egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla',
            'is_important' => true,
            'created_at' => '2016-08-26 20:34:10',
            'updated_at' => '2016-01-21 03:56:57',
        ],
        [
            'id' => 49,
            'code' => 'Tellus Corp.',
            'lang' => 'en',
            'title' => 'eu, euismod ac,',
            'link_title' => 'in lobortis tellus justo',
            'content' => 'Vestibulum ut eros non enim commodo hendrerit.',
            'is_important' => true,
            'created_at' => '2016-11-16 23:53:43',
            'updated_at' => '2016-11-17 05:19:25',
        ],
        [
            'id' => 50,
            'code' => 'Purus In Molestie Corporation',
            'lang' => 'en',
            'title' => 'posuere cubilia Curae Phasellus',
            'link_title' => 'tempus non, lacinia at,',
            'content' => 'mi tempor lorem, eget mollis lectus pede et risus. Quisque',
            'is_important' => true,
            'created_at' => '2016-06-15 10:17:36',
            'updated_at' => '2015-07-10 19:17:18',
        ],
    ],
    'settings' => [
        ['id' => 1, 'key' => 'Wommelgem', 'value' => 'vitae'],
        ['id' => 2, 'key' => 'Lota', 'value' => 'Quisque'],
        ['id' => 3, 'key' => 'General Lagos', 'value' => 'nisl sem,'],
        ['id' => 4, 'key' => 'Vielsalm', 'value' => 'dui quis'],
        ['id' => 5, 'key' => "Rio nell'Elba", 'value' => 'auctor quis, tristique'],
        ['id' => 6, 'key' => 'Lens-Saint-Remy', 'value' => 'dui quis accumsan'],
        ['id' => 7, 'key' => 'Trollhättan', 'value' => 'quis,'],
        ['id' => 8, 'key' => 'Fulda', 'value' => 'neque venenatis'],
        ['id' => 9, 'key' => 'Itter', 'value' => 'vehicula aliquet libero.'],
        ['id' => 10, 'key' => 'Appelterre-Eichem', 'value' => 'eros turpis'],
        ['id' => 11, 'key' => 'Guysborough', 'value' => 'augue eu tellus.'],
        ['id' => 12, 'key' => 'Bally', 'value' => 'faucibus'],
        ['id' => 13, 'key' => 'Mol', 'value' => 'Nunc'],
        ['id' => 14, 'key' => 'Overmere', 'value' => 'Suspendisse non leo.'],
        ['id' => 15, 'key' => 'Brunn am Gebirge', 'value' => 'aliquet vel, vulputate'],
        ['id' => 16, 'key' => 'San Martino in Pensilis', 'value' => 'Nunc sed orci'],
        ['id' => 17, 'key' => 'Piotrków Trybunalski', 'value' => 'pellentesque,'],
        ['id' => 18, 'key' => 'Acquafredda', 'value' => 'Aliquam'],
        ['id' => 19, 'key' => 'Groot-Bijgaarden', 'value' => 'ut erat.'],
        ['id' => 20, 'key' => 'Bargagli', 'value' => 'morbi tristique'],
        ['id' => 21, 'key' => 'Timaukel', 'value' => 'ante'],
        ['id' => 22, 'key' => 'Dessel', 'value' => 'adipiscing'],
        ['id' => 23, 'key' => 'Naperville', 'value' => 'at'],
        ['id' => 24, 'key' => 'Merzig', 'value' => 'ut'],
        ['id' => 25, 'key' => 'Farrukhabad-cum-Fatehgarh', 'value' => 'Integer mollis.'],
        ['id' => 26, 'key' => 'San Chirico Nuovo', 'value' => 'pede'],
        ['id' => 27, 'key' => 'Antuco', 'value' => 'congue. In scelerisque'],
        ['id' => 28, 'key' => 'Freire', 'value' => 'scelerisque sed, sapien.'],
        ['id' => 29, 'key' => 'Landau', 'value' => 'Sed pharetra,'],
        ['id' => 30, 'key' => 'Bonn', 'value' => 'aliquet vel, vulputate'],
        ['id' => 31, 'key' => 'MŽlin', 'value' => 'sem, vitae aliquam'],
        ['id' => 32, 'key' => 'Redlands', 'value' => 'eu dui. Cum'],
        ['id' => 33, 'key' => 'Sint-Pieters-Leeuw', 'value' => 'enim. Sed nulla'],
        ['id' => 34, 'key' => 'Meeuwen-Gruitrode', 'value' => 'imperdiet'],
        ['id' => 35, 'key' => 'Kruibeke', 'value' => 'hendrerit. Donec porttitor'],
        ['id' => 36, 'key' => 'Sandviken', 'value' => 'magna.'],
        ['id' => 37, 'key' => 'Caledon', 'value' => 'ac'],
        ['id' => 38, 'key' => 'Sabadell', 'value' => 'nunc, ullamcorper'],
        ['id' => 39, 'key' => 'Hampstead', 'value' => 'tellus, imperdiet non,'],
        ['id' => 40, 'key' => 'Norrköping', 'value' => 'Phasellus libero mauris,'],
        ['id' => 41, 'key' => 'Heredia', 'value' => 'sit amet ante.'],
        ['id' => 42, 'key' => 'Segni', 'value' => 'magna. Sed eu'],
        ['id' => 43, 'key' => 'Muridke', 'value' => 'dis parturient'],
        ['id' => 44, 'key' => 'Portland', 'value' => 'justo faucibus lectus,'],
        ['id' => 45, 'key' => 'Kassel', 'value' => 'mollis'],
        ['id' => 46, 'key' => 'Arsoli', 'value' => 'tempus'],
        ['id' => 47, 'key' => 'Otegem', 'value' => 'arcu. Vestibulum'],
        ['id' => 48, 'key' => 'Zoetermeer', 'value' => 'dolor.'],
        ['id' => 49, 'key' => 'Ereğli', 'value' => 'Integer'],
        ['id' => 50, 'key' => 'Mandi Burewala', 'value' => 'sagittis placerat.'],
    ],
];
