CREATE DATABASE "pesky_orm_test_db" UTF8 general_ci

CREATE USER 'pesky_orm_test'@'' IDENTIFIED BY '1111111';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `pesky\_orm\_test\_db`.* TO 'pesky_orm_test'@'';